// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © DamiSneeze

//@version=6
indicator("The Method", overlay = true)
// import TradingView/ta/12
// ^ where did this come from?

// SETTINGS
// All customizability and inputs that this indicator will use

//Group - Fair Value Gap (FVG)
bool fvg_multiTF = input.bool(true, "FVG Multi TimeFrame Display Toggle", 
"""Determines if Fair Value Gaps are pulled from multiple timeframes and displayed in an overlay.""",
group='Fair Value Gaps')
float fvg_min_size = input.float(0.15, "Minimum FVG Size", minval=0,
tooltip="""Determines the minimum size that a FVG can be. Can be used to prevent very small FVGs that are indistinguisable from a line.""",
group='Fair Value Gaps')

// TYPES
// All types and enums used to store/display information


//@enum An enumeration of the bullish or bearish sentiment of a
// liquidity zone. (FVGs, Liquidity Pools, etc.)
//@field BULL  Specifies a liquidity zone where buyers are likely to make a move.
//@field BEAR  Specifies a liquidity zone where sellers are likely to make a move.
enum sentiment
    BULL
    BEAR

//@enum An enumeration of the status of zones of liquidity
// that price can react of off. (FVGs, Liquidity Pools, etc.)
//@field OPEN   Specifies a zone that price has not disrespected.
//@field MITIGATED   Specifies a zone that price has gone more than 50% through.
//@field CLOSED  Specifies a zone that price has closed beyond.
enum status
    OPEN
    MITIGATED
    CLOSED

//@type A custom object that holds information on a Fair Value Gap.
//@field top  Stores the top price of the FVG. The point price must close beyond to 
// invalidate a bearish FVG.
//@field bottom  Stores the bottom price of the FVG. The point price must close beyond to 
// invalidate a bullish FVG.
//@field middle  Stores the middle price of the FVG.
//@field start  Stores the bar_index that a FVG starts from.
//@field direction  Stores an enumeration value for the sentiment of bullish or bearish.
//@field fvg_status  Stores an enumeration value for whether the FVG is open, mitigated, or closed.
//@field display  Stores the box object that is displayed on the chart.
//@field midline  Stores the line object that displays the middle of the FVG.
//@field bounce_line Stores a line object representing where price must close
// beyond in order to invalidate a FVG. Only appears when fvg_status == status.MITIGATED. 
type fvg
    float top
    float bottom
    float middle
    int start
    sentiment direction
    status fvg_status
    box display
    line midline
    line bounce_line


//FUNCTIONS
// Reusable code that will be repeatedly called on

//@function This function checks the last bar (low[1]/high[1]) and
// the bar from three candles ago (low[3]/high[3]); creating
// a FVG object after it identifies whether a gap exists
// between them.
detect_fvg() =>
    fvg FVG = na
    if high[3] < low[1] and (low[1] - high[3] > fvg_min_size)
        int start = bar_index - 2
        float top = low[1]
        float bottom = high[3]
        float middle = math.avg(top, bottom)

        FVG := fvg.new(top, bottom, middle, start, sentiment.BULL, status.OPEN)

    else if low[3] > high[1] and (low[3] - high[1] > fvg_min_size)
        int start = bar_index - 2
        float top = low[3]
        float bottom = high[1]
        float middle = math.avg(top, bottom)

        FVG := fvg.new(top, bottom, middle, start, sentiment.BEAR, status.OPEN)

    FVG

plot_fvg(fvg FVG, array<fvg> bull_arr, array<fvg> bear_arr) => 
    int start = FVG.start
    chart.point top = chart.point.from_index(start, FVG.top)
    chart.point bottom = chart.point.from_index(start, FVG.bottom)
    chart.point midpoint1 = chart.point.from_index(start, FVG.middle)
    chart.point midpoint2 = chart.point.from_index(bar_index, FVG.middle)

    if FVG.direction == sentiment.BULL
        FVG.display := box.new(top, bottom, border_width=0, bgcolor=color.new(color.blue, 85), extend=extend.right)
        FVG.midline := line.new(midpoint1, midpoint2, color=color.blue, extend=extend.right)
        bull_arr.unshift(FVG)

    else if FVG.direction == sentiment.BEAR
        FVG.display := box.new(top, bottom, border_width=0, bgcolor=color.new(color.orange, 85), extend=extend.right)
        FVG.midline := line.new(midpoint1, midpoint2, color=color.orange, extend=extend.right)
        bear_arr.unshift(FVG)

update_bullish_fvgs(array<fvg> bull_arr) =>
    array<int> closed_idxs = array.new<int>()
    for [idx, FVG] in bull_arr
        if (barstate.ishistory or barstate.isconfirmed) and close < FVG.bottom
            box.delete(FVG.display)
            line.delete(FVG.midline)
            if not na(FVG.bounce_line)
                line.delete(FVG.bounce_line)
            array.unshift(closed_idxs, idx)
            continue
        if low < FVG.middle and FVG.fvg_status != status.MITIGATED
            box bx = FVG.display
            line ln = FVG.midline
            box.set_right(bx, bar_index)
            box.set_extend(bx, extend.none)
            box.set_bgcolor(bx, color.new(color.silver, 50))
            line.set_x2(ln, bar_index)
            line.set_extend(ln, extend.none)
            line.set_color(ln, color.black)
            chart.point bouncepoint1 = chart.point.from_index(FVG.start, FVG.bottom)
            chart.point bouncepoint2 = chart.point.from_index(bar_index, FVG.bottom)
            FVG.bounce_line := line.new(bouncepoint1, bouncepoint2, extend=extend.right, color=color.new(color.blue, 50), width=3)
            FVG.fvg_status := status.MITIGATED
            continue
        if low > FVG.middle
            break
    
    // Going through FVG stack and adding the closed indexes as their own stack
    // to prohibit a deleted index from changing the location of the next 
    // FVG(s) to delete
    for idx in closed_idxs
        array.remove(bull_arr, idx)

update_bearish_fvgs(array<fvg> bear_arr) =>
    array<int> closed_idxs = array.new<int>()
    for [idx, FVG] in bear_arr
        if (barstate.ishistory or barstate.isconfirmed) and close > FVG.top
            box.delete(FVG.display)
            line.delete(FVG.midline)
            if not na(FVG.bounce_line)
                line.delete(FVG.bounce_line)
            array.unshift(closed_idxs, idx)
            continue
        if high > FVG.middle and FVG.fvg_status != status.MITIGATED
            box bx = FVG.display
            line ln = FVG.midline
            box.set_right(bx, bar_index)
            box.set_extend(bx, extend.none)
            box.set_bgcolor(bx, color.new(color.silver, 50))
            line.set_x2(ln, bar_index)
            line.set_extend(ln, extend.none)
            line.set_color(ln, color.black)
            chart.point bouncepoint1 = chart.point.from_index(FVG.start, FVG.top)
            chart.point bouncepoint2 = chart.point.from_index(bar_index, FVG.top)
            FVG.bounce_line := line.new(bouncepoint1, bouncepoint2, extend=extend.right, color=color.new(color.orange, 50), width=3)
            FVG.fvg_status := status.MITIGATED
            continue
        if high < FVG.middle
            break
    
    for idx in closed_idxs
        array.remove(bear_arr, idx)


// RUNTIME
// Line of logic that is run for every bar execution


// Fair Value Gaps
var array<fvg> fvgs_bull = array.new<fvg>()
var array<fvg> fvgs_bear = array.new<fvg>()

// if not fvg_multiTF
fvg FVG = detect_fvg()
if not na(FVG)
    plot_fvg(FVG, fvgs_bull, fvgs_bear)

if fvgs_bull.size() > 0
    update_bullish_fvgs(fvgs_bull)

if fvgs_bear.size() > 0
    update_bearish_fvgs(fvgs_bear)
// else
    // fvg FVG = request.security(syminfo.tickerid, "30", detect_fvg(fvgs_bull, fvgs_bear))

//sort fvgs array by midline not terminal_price for bug fix foresight
//current colors are placeholders
//Implement liquidity pools using RSI of close of hlc(c)
// add setting for fvgs to only be made from candle during market hours
//could turn closed_idxs loop into a separate garbage collector func
