// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © DamiSneeze

//@version=6
indicator("The Method", overlay = true)

// Settings
// All customizability and inputs that this indicator will use

//Group - Fair Value Gap (FVG)
bool fvg_multiTF = input.bool(true, "FVG Multi TimeFrame Display", 
"""Determines if Fair Value Gaps are pulled from multiple timeframes
     and displayed in an overlay""", 'fvg', 'Fair Value Gaps')



// Types
// All types and enums used to store/display information

enum sentiment
    BULL
    BEAR

enum status
    MITIGATED
    OPEN
    CLOSED

type fvg
    box display
    line midline
    float mid_price
    float terminal_price
    int start
    sentiment direction
    status fvg_status
    line bounce_line


// Runtime
// Line of logic that is run for every bar execution


// Fair Value Gaps
var array<fvg> fvgs_bull = array.new<fvg>()
var array<fvg> fvgs_bear = array.new<fvg>()

fvg FVG = na
if high[3] < low[1]
    int start = bar_index - 2
    chart.point top = chart.point.from_index(start, low[1])
    chart.point bottom = chart.point.from_index(start, high[3])
    float middle = math.avg(top.price, bottom.price)

    chart.point midpoint1 = chart.point.from_index(start, middle)
    chart.point midpoint2 = chart.point.from_index(bar_index, middle)

    box bx = box.new(top, bottom, bgcolor=color.new(color.blue, 70), extend = extend.right)
    line ln = line.new(midpoint1, midpoint2, color=color.blue, extend=extend.right)

    FVG := fvg.new(bx, ln, middle, bottom.price, start, sentiment.BULL, status.OPEN)
    fvgs_bull.unshift(FVG)



if fvgs_bull.size() > 0
    int num_closed = 0  
    for i in fvgs_bull
        if (barstate.ishistory or barstate.isconfirmed) and close < i.terminal_price
            box.delete(i.display)
            line.delete(i.midline)
            if not na(i.bounce_line)
                line.delete(i.bounce_line)
            num_closed += 1
        else if low < i.mid_price and i.fvg_status != status.MITIGATED
            box bx = i.display
            line ln = i.midline
            box.set_right(bx, bar_index)
            box.set_extend(bx, extend.none)
            box.set_bgcolor(bx, color.new(color.silver, 50))
            line.set_x2(ln, bar_index)
            line.set_extend(ln, extend.none)
            line.set_color(ln, color.black)
            chart.point bouncepoint1 = chart.point.from_index(i.start, i.terminal_price)
            chart.point bouncepoint2 = chart.point.from_index(bar_index, i.terminal_price)
            i.bounce_line := line.new(bouncepoint1, bouncepoint2, extend=extend.right, color=color.new(color.blue, 70), width=3)
            i.fvg_status := status.MITIGATED
        else if low > i.mid_price
            if num_closed > 0
                for j = 0 to num_closed - 1 by 1
                    array.shift(fvgs_bull)
            break

//sort fvgs array by midline not terminal_price for bug fix foresight
//current colors are placeholders
//Implement liquidity pools using RSI of close of hlc(c)
