// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © DamiSneeze

//@version=6
indicator("The Method", overlay = true)

// Settings
// All customizability and inputs that this indicator will use

//Group - Fair Value Gap (FVG)
bool fvg_multiTF = input.bool(true, "FVG Multi TimeFrame Display", 
"""Determines if Fair Value Gaps are pulled from multiple timeframes
     and displayed in an overlay""", 'fvg', 'Fair Value Gaps')



// Types
// All types and enums used to store/display information

enum sentiment
    BULL
    BEAR

enum status
    MITIGATED
    OPEN
    CLOSED

type fvg
    box display
    line midline
    float terminal_price
    int start
    sentiment direction
    status fvg_status
    line bounce_line


// Runtime
// Line of logic that is run for every bar execution


// Fair Value Gaps
var array<fvg> fvgs_bull = na
var array<fvg> fvgs_bear = na

fvg FVG = na
if high[3] < low[1]
    int start = bar_index - 2
    chart.point top = chart.point.from_index(start, high[3])
    chart.point bottom = chart.point.from_index(start, low[1])
    float middle = math.avg(top.price, bottom.price)

    chart.point midline1 = chart.point.from_index(start, middle)
    chart.point midline2 = chart.point.from_index(bar_index, middle)

    box bx = box.new(top, bottom, bgcolor=color.new(color.blue, 70), extend = extend.right)
    line ln = line.new(midline1, midline2, color=color.blue, extend=extend.right)

    FVG := fvg.new(bx, ln, bottom.price, start, sentiment.BULL, status.OPEN)
    fvgs_bull.unshift(FVG)
    

//Implement liquidity pools using RSI of close of hlc(c)
